### PR TITLE
Add support for Maven and Gradle projects

### LINKED ISSUE #3: NullPointerException: The buildXml parameter cannot be null
When I try to run a file with this plugin I get NPE. I reported the crash through Nebeans 8, see https://netbeans.org/bugzilla/show_bug.cgi?id=243737

The file is a part of a maven project, so maybe this is the problem (?)

### PR DESCRIPTION
**Pull request by kkofler**
Fixes #3.

### CODE REVIEW

**Comment by kkofler** [comment]
Ping? Is this project still alive?

**Comment by kkofler** [comment]
Ping? Is this project still alive?

**Comment by kkofler** [comment]
Since I have not received an answer for more than 5 months now, I have uploaded a release to my fork:
https://github.com/kkofler/nbrunwithargs/releases/tag/3.0
The uploaded binary has been tested by me and by a few of my colleagues. It should work with NetBeans ≥ 8.0.

**Comment by kkofler** [comment]
If I make further improvements/fixes, you will find them under: https://github.com/kkofler/nbrunwithargs/releases

**Comment by tusharjoshi** [comment]
Thanks for the update.  I haven't checked this PR thoroughly but have merged in as you mentioned it is in release mode.  I was away from this plugin for some years, now and appreciate the update provided.

I will test the update on my end now onwards

**Comment by kkofler** [comment]
Thanks for your reply. If you do official releases, I will point users to your releases rather than mine.

You should probably also try to get the copy in the NetBeans plugin repository updated. Though unfortunately I am not sure whether my reflection hackery will pass their QA. But I do not see any other way to get the plugin to interact with the Maven and Gradle plugins the way it has to do.

**Pull request merged**
